repos:
-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.0
    hooks:
    - id: sqlfluff-lint
      additional_dependencies: ['dbt-athena', 'sqlfluff-templater-dbt']
    - id: sqlfluff-fix
      additional_dependencies: ['dbt-athena', 'sqlfluff-templater-dbt']