[project]
name = "starship-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-postgres>=1.9.0",
    "sqlfluff>=3.4.2",
]
